version: "3.1"

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    #    ports:
    #      - 9030:8080
    networks:
      - database

  postgres:
    build:
      context: ./images
      dockerfile: postgres.dockerfile
    image: hiramlabs/postgres
    container_name: postgres
    restart: unless-stopped
    #    ports:
    #      - 9031:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./dump:/var/backups
    networks:
      - database

  influxdb:
    build:
      context: ./images
      dockerfile: influxdb.dockerfile
    image: hiramlabs/influxdb
    container_name: influxdb
    restart: unless-stopped
    #    ports:
    #      - 9032:8086
    volumes:
      - influx_data:/var/lib/influxdb2
      - ./dump:/var/backups
    networks:
      - database

  neo4j:
    build:
      context: ./images
      dockerfile: neo4j.dockerfile
    image: hiramlabs/neo4j
    container_name: neo4j
    restart: unless-stopped
    #    ports:
    #      - 9033:7687
    #      - 9034:7474
    volumes:
      - neo4j_data:/data
      - ./dump:/backups
    networks:
      - database

  cayley:
    build:
      context: ./images
      dockerfile: cayley.dockerfile
    image: hiramlabs/cayley
    container_name: cayley
    restart: unless-stopped
    #    ports:
    #      - 9035:64210
    volumes:
      - cayley_data:/data
      - ./dump:/backups
    networks:
      - database

  redis:
    build:
      context: ./images
      dockerfile: redis.dockerfile
    image: hiramlabs/redis
    container_name: redis
    restart: unless-stopped
    #    ports:
    #      - 9036:6379
    volumes:
      - ./dump:/backups
    networks:
      - database

  rabbitmq:
    build:
      context: ./images
      dockerfile: rabbitmq.dockerfile
    image: hiramlabs/rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    #    ports:
    #      - 9037:5672
    #      - 9038:15672
    networks:
      - database

volumes:
  pg_data:
  influx_data:
  neo4j_data:
  cayley_data:

networks:
  database:
    external:
      name: database
